# Site settings
title: IndigiAutolabs
email: indigiautolabs@gmail.com
url: https://bhavk26.github.io/IndigiAutolabs/
description: "Tech Consultancy Services"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: IndigiAutolabs

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/bhavesh-kumar-75a101126/
 # - title: facebook
 #   url:
 # - title: stack-overflow
 #  url: http://stackoverflow.com/questions/tagged/jekyll
 #  - title: bitbucket
 #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/bhavk26

# Build settings
markdown: kramdown
permalink: pretty
